name: Run_Adblock_Reject_DOMAIN_TXT

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PowerShell 7
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        rm packages-microsoft-prod.deb

    - name: Install Python 3 and dependencies
      run: |
        sudo apt-get install python3 python3-pip -y
        pip3 install requests

    - name: Run adblock_rule_generator_domain_txt.ps1
      run: pwsh -File ./adblock_rule_generator_domain_txt.ps1

    - name: Run Python script to generate JSON (Optional step if needed)
      run: python3 ./generate_singbox_json.py  # This step is for generating the JSON file

    - name: Force Add and Commit Txt file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f adblock_reject_domain.txt
        git commit -m 'Update adblock_reject_domain.txt' || git commit --allow-empty -m 'Empty commit to force push'

    - name: Retry Push Txt file
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        for i in {1..5}; do
          git push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
        done
