name: Run_Adblock_Reject_DOMAIN_TXT

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PowerShell 7
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        rm packages-microsoft-prod.deb

    - name: Run adblock_rule_generator_domain_txt.ps1
      run: pwsh -File ./adblock_rule_generator_domain_txt.ps1

    - name: Verify JSON file is generated
      run: |
        if [ -f ./adblock_reject_domain.json ]; then
          echo "JSON file generated successfully!"
        else
          echo "JSON file not generated. Please check the script."
          exit 1
        fi

    - name: Force Add and Commit Txt file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f adblock_reject_domain.txt
        git add -f adblock_reject_domain.json
        git commit -m 'Update adblock_reject_domain.txt and adblock_reject_domain.json' || git commit --allow-empty -m 'Empty commit to force push'

    - name: Retry Push Txt and JSON files
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        for i in {1..5}; do
          git push --force origin HEAD && exit 0 || (echo "Push failed, retrying in 10 seconds..." && sleep 10)
        done
